apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project:
  source:
    repoURL: https://github.com/nhelsherif/gitops-examples.git
    targetRevision: HEAD
    path: apps
  syncPolicy:
    automated: {}
